name = "willowworker"
main = "src/worker.js"
compatibility_date = "2025-08-01"

[triggers]
crons = ["0 13 * * *"] # run daily at 13:00 UTC

[[kv_namespaces]]
binding = "willow_forecasts"
id = "1d363298cbf24016b5cb535c7da48613"
# preview_id = "<YOUR_PREVIEW_ID>" # optional
